apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: hi-indore-hpa
    namespace: development
    labels:
        app: hi-indore
        tier: frontend
spec:
    scaleTargetRef:
        apiVersion: apps/v1beta1
        kind: Deployment
        name: hi-indore
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 10
